- name: Commit and push playlist
  run: |
    git config user.name "github-actions"
    git config user.email "github-actions@github.com"
    git add -A
    git commit -m "M3U güncellendi: $(date -u)" || echo "Değişiklik yok, commit atlanıyor"
    git push
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
